# Generated by Django 3.1.5 on 2021-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='n',
            field=models.IntegerField(default=1),
        ),
    ]
