# Generated by Django 3.1.5 on 2021-04-17 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20210417_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
