"""
Django settings for recommender_app project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import pandas as pd
import numpy as np
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ih8i4(qxqcpc4w2nnconr3eo8w3@rr^&w@y)%-#cb)83f3%-%h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'recommender',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recommender_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'recommender_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'


movies_file = os.path.join(BASE_DIR, "data", "movies.csv")
columns_file = os.path.join(BASE_DIR, "data","metric_columns.txt")
df = pd.read_csv(movies_file)
df["popularity"] = np.minimum(df["popularity"], 25)

metric_columns = ["id",
                    "popularity",
                    "vote_average",
                    "vote_count",
                    "age",
                    "release_date",
                    "runtime",
                    "adult",
                    "Thriller",
                    "Action",
                    "Family",
                    "GoHands",
                    "Drama",
                    "Crime",
                    "Comedy",
                    "War",
                    "Fantasy",
                    "Horror",
                    "Mystery",
                    "Music",
                    "Foreign",
                    "Adventure",
                    "Romance",
                    "History",
                    "Western",
                    "Animation",
                    "Documentary",
                    "Science Fiction",
                    "language_en",
                    "language_fr",
                    "language_it",
                    "language_ja",
                    "language_de",
                    "language_es",
                    "language_ru",
                    "language_hi",
                    "language_ko",
                    "language_zh",
                    "language_sv",
                    "language_pt",
                    "language_cn",
                    "language_fi",
                    "language_nl",
                    "language_da",
                    "language_pl",
                    "language_tr",
                    "language_cs",
                    "language_el",
                    "language_no",
                    "language_fa",
                    "language_hu",
                    "language_ta",
                    "language_th",
                    "language_he",
                    "language_sr",
                    "language_ro",
                    "language_te",
                    "language_ar",
                    "language_ml",
                    "language_xx",
                    "language_bn",
                    "language_hr",
                    "language_mr",
                    "language_is",
                    "language_et",
                    "language_tl",
                    "language_id",
                    "language_ka",
                    "Paramount Pictures",
                    "Metro-Goldwyn-Mayer (MGM)",
                    "Twentieth Century Fox Film Corporation",
                    "Warner Bros.",
                    "Universal Pictures",
                    "Columbia Pictures",
                    "Columbia Pictures Corporation",
                    "RKO Radio Pictures",
                    "United Artists",
                    "Walt Disney Pictures",
                    "New Line Cinema",
                    "Mosfilm",
                    "Miramax Films",
                    "TriStar Pictures",
                    "Toho Company",
                    "Gaumont",
                    "BBC Films",
                    "Orion Pictures",
                    "Touchstone Pictures",
                    "France 2 Cinéma",
                    "Fox Searchlight Pictures",
                    "Walt Disney Productions",
                    "Village Roadshow Pictures",
                    "Universal International Pictures (UI)",
                    "British Broadcasting Corporation (BBC)",
                    "Shaw Brothers",
                    "DreamWorks SKG",
                    "Hammer Film Productions",
                    "Channel Four Films",
                    "TLA Releasing",
                    "Lions Gate Films",
                    "First National Pictures",
                    "New World Pictures",
                    "The Rank Organisation",
                    "Nikkatsu",
                    "Canal+",
                    "American International Pictures (AIP)",
                    "Lionsgate",
                    "Regency Enterprises",
                    "Shôchiku Eiga",
                    "StudioCanal",
                    "Monogram Pictures",
                    "Nordisk Film",
                    "Imagine Entertainment",
                    "Fox Film Corporation",
                    "CJ Entertainment",
                    "Hollywood Pictures",
                    "Summit Entertainment",
                    "Rai Cinema",
                    "United States of America",
                    "United Kingdom",
                    "France",
                    "Canada",
                    "Japan",
                    "Italy",
                    "Germany",
                    "Russia",
                    "India",
                    "Spain",
                    "Australia",
                    "Hong Kong",
                    "South Korea",
                    "Sweden",
                    "Finland",
                    "China",
                    "Belgium",
                    "Denmark",
                    "Brazil",
                    "Poland",
                    "Mexico",
                    "Netherlands",
                    "Argentina",
                    "Czech Republic",
                    "Austria",
                    "Ireland",
                    "Turkey",
                    "Greece",
                    "Norway"]
model_columns = metric_columns[5:]



genres = ['Thriller', 'Action', 'Family', 'Drama', 'Crime', 'Comedy', 'War',  'Fantasy', 'Horror', 'Mystery', 'Music', 
          'Foreign', 'Adventure', 'Romance', 'History', 'Western', 'Animation', 'Documentary', 'Science Fiction']
